In [ ]:
# Update sklearn to prevent version mismatches
#!pip install sklearn --upgrade

In [ ]:
# install joblib. This will be used to save your model. 
# Restart your kernel after installing 
#!pip install joblib

In [37]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# Read the CSV and Perform Basic Data Cleaning

In [38]:
df = pd.read_csv("exoplanet_data.csv")
# Drop the null columns where all values are null
df = df.dropna(axis='columns', how='all')
# Drop the null rows
df = df.dropna()
df

koi_disposition  koi_fpflag_nt  koi_fpflag_ss  koi_fpflag_co  \
0          CONFIRMED              0              0              0   
1     FALSE POSITIVE              0              1              0   
2     FALSE POSITIVE              0              1              0   
3          CONFIRMED              0              0              0   
4          CONFIRMED              0              0              0   
...              ...            ...            ...            ...   
6986  FALSE POSITIVE              0              0              0   
6987  FALSE POSITIVE              0              1              1   
6988       CANDIDATE              0              0              0   
6989  FALSE POSITIVE              0              0              1   
6990  FALSE POSITIVE              0              0              1   

      koi_fpflag_ec  koi_period  koi_period_err1  koi_period_err2  \
0                 0   54.418383     2.479000e-04    -2.479000e-04   
1                 0   19.899140     1.490000e-05    -1.490000e-05   
2                 0    1.736952     2.630000e-07    -2.630000e-07   
3                 0    2.525592     3.760000e-06    -3.760000e-06   
4                 0    4.134435     1.050000e-05    -1.050000e-05   
...             ...         ...              ...              ...   
6986              1    8.589871     1.846000e-04    -1.846000e-04   
6987              0    0.527699     1.160000e-07    -1.160000e-07   
6988              0    1.739849     1.780000e-05    -1.780000e-05   
6989              0    0.681402     2.430000e-06    -2.430000e-06   
6990              1    4.856035     6.360000e-05    -6.360000e-05   

      koi_time0bk  koi_time0bk_err1  ...  koi_steff_err2  koi_slogg  \
0      162.513840          0.003520  ...             -81      4.467   
1      175.850252          0.000581  ...            -176      4.544   
2      170.307565          0.000115  ...            -174      4.564   
3      171.595550          0.001130  ...            -211      4.438   
4      172.979370          0.001900  ...            -232      4.486   
...           ...               ...  ...             ...        ...   
6986   132.016100          0.015700  ...            -152      4.296   
6987   131.705093          0.000170  ...            -166      4.529   
6988   133.001270          0.007690  ...            -220      4.444   
6989   132.181750          0.002850  ...            -236      4.447   
6990   135.993300          0.010800  ...            -225      4.385   

      koi_slogg_err1  koi_slogg_err2  koi_srad  koi_srad_err1  koi_srad_err2  \
0              0.064          -0.096     0.927          0.105         -0.061   
1              0.044          -0.176     0.868          0.233         -0.078   
2              0.053          -0.168     0.791          0.201         -0.067   
3              0.070          -0.210     1.046          0.334         -0.133   
4              0.054          -0.229     0.972          0.315         -0.105   
...              ...             ...       ...            ...            ...   
6986           0.231          -0.189     1.088          0.313         -0.228   
6987           0.035          -0.196     0.903          0.237         -0.079   
6988           0.056          -0.224     1.031          0.341         -0.114   
6989           0.056          -0.224     1.041          0.341         -0.114   
6990           0.054          -0.216     1.193          0.410         -0.137   

             ra        dec  koi_kepmag  
0     291.93423  48.141651      15.347  
1     297.00482  48.134129      15.436  
2     285.53461  48.285210      15.597  
3     288.75488  48.226200      15.509  
4     296.28613  48.224670      15.714  
...         ...        ...         ...  
6986  298.74921  46.973351      14.478  
6987  297.18875  47.093819      14.082  
6988  286.50937  47.163219      14.757  
6989  294.16489  47.176281      15.385  
6990  297.00977  47.121021      14.826  

[6991 rows x 41 columns]

# Select your features (columns)

In [39]:
# Set features. This will also be used as your x values.
#selected_features = df.drop(['koi_disposition'], axis = 1)
X = df.drop(['koi_disposition'], axis = 1)
X

koi_fpflag_nt  koi_fpflag_ss  koi_fpflag_co  koi_fpflag_ec  koi_period  \
0                 0              0              0              0   54.418383   
1                 0              1              0              0   19.899140   
2                 0              1              0              0    1.736952   
3                 0              0              0              0    2.525592   
4                 0              0              0              0    4.134435   
...             ...            ...            ...            ...         ...   
6986              0              0              0              1    8.589871   
6987              0              1              1              0    0.527699   
6988              0              0              0              0    1.739849   
6989              0              0              1              0    0.681402   
6990              0              0              1              1    4.856035   

      koi_period_err1  koi_period_err2  koi_time0bk  koi_time0bk_err1  \
0        2.479000e-04    -2.479000e-04   162.513840          0.003520   
1        1.490000e-05    -1.490000e-05   175.850252          0.000581   
2        2.630000e-07    -2.630000e-07   170.307565          0.000115   
3        3.760000e-06    -3.760000e-06   171.595550          0.001130   
4        1.050000e-05    -1.050000e-05   172.979370          0.001900   
...               ...              ...          ...               ...   
6986     1.846000e-04    -1.846000e-04   132.016100          0.015700   
6987     1.160000e-07    -1.160000e-07   131.705093          0.000170   
6988     1.780000e-05    -1.780000e-05   133.001270          0.007690   
6989     2.430000e-06    -2.430000e-06   132.181750          0.002850   
6990     6.360000e-05    -6.360000e-05   135.993300          0.010800   

      koi_time0bk_err2  ...  koi_steff_err2  koi_slogg  koi_slogg_err1  \
0            -0.003520  ...             -81      4.467           0.064   
1            -0.000581  ...            -176      4.544           0.044   
2            -0.000115  ...            -174      4.564           0.053   
3            -0.001130  ...            -211      4.438           0.070   
4            -0.001900  ...            -232      4.486           0.054   
...                ...  ...             ...        ...             ...   
6986         -0.015700  ...            -152      4.296           0.231   
6987         -0.000170  ...            -166      4.529           0.035   
6988         -0.007690  ...            -220      4.444           0.056   
6989         -0.002850  ...            -236      4.447           0.056   
6990         -0.010800  ...            -225      4.385           0.054   

      koi_slogg_err2  koi_srad  koi_srad_err1  koi_srad_err2         ra  \
0             -0.096     0.927          0.105         -0.061  291.93423   
1             -0.176     0.868          0.233         -0.078  297.00482   
2             -0.168     0.791          0.201         -0.067  285.53461   
3             -0.210     1.046          0.334         -0.133  288.75488   
4             -0.229     0.972          0.315         -0.105  296.28613   
...              ...       ...            ...            ...        ...   
6986          -0.189     1.088          0.313         -0.228  298.74921   
6987          -0.196     0.903          0.237         -0.079  297.18875   
6988          -0.224     1.031          0.341         -0.114  286.50937   
6989          -0.224     1.041          0.341         -0.114  294.16489   
6990          -0.216     1.193          0.410         -0.137  297.00977   

            dec  koi_kepmag  
0     48.141651      15.347  
1     48.134129      15.436  
2     48.285210      15.597  
3     48.226200      15.509  
4     48.224670      15.714  
...         ...         ...  
6986  46.973351      14.478  
6987  47.093819      14.082  
6988  47.163219      14.757  
6989  47.176281      15.385  
6990  47.121021      14.826  

[6991 rows x 40 c

# Create a Train Test Split

Use `koi_disposition` for the y values

In [108]:
y = df[['koi_disposition']]
#print(y)
new_data = {"CONFIRMED":1, "CANDIDATE":2, "FALSE POSITIVE":3}
y = y.replace({"koi_disposition":new_data})
#print(y)
y = np.ravel(y)
print(y)

[1 3 3 ... 2 3 3]


In [109]:
#y = df['koi_disposition']
#print(y)
#data_dummies = pd.get_dummies(y)
#print(data_dummies)
#y = data_dummies["CONFIRMED"].values
#print(y)

In [110]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.2)

X_train.shape, X_test.shape, y_train.shape, y_test.shape
#y_train

((5592, 40), (1399, 40), (5592,), (1399,))

In [111]:
X_train

koi_fpflag_nt  koi_fpflag_ss  koi_fpflag_co  koi_fpflag_ec  koi_period  \
1128              0              0              0              0  134.478519   
1842              0              0              0              0    5.308740   
5681              0              1              0              0    2.025580   
4295              1              0              0              0    1.000841   
1729              0              0              0              0    5.838930   
...             ...            ...            ...            ...         ...   
3462              0              0              1              0    0.821472   
6568              0              1              0              0    3.457079   
4570              1              0              0              0    1.434200   
2916              0              0              0              0    2.894947   
4080              0              0              0              0  132.133101   

      koi_period_err1  koi_period_err2  koi_time0bk  koi_time0bk_err1  \
1128     1.705000e-04    -1.705000e-04   169.281410          0.001030   
1842     4.550000e-05    -4.550000e-05   134.250610          0.006400   
5681     2.710000e-07    -2.710000e-07   131.864175          0.000111   
4295     6.440000e-07    -6.440000e-07   121.293771          0.000561   
1729     2.050000e-05    -2.050000e-05   136.902930          0.002940   
...               ...              ...          ...               ...   
3462     9.900000e-06    -9.900000e-06   132.300300          0.012000   
6568     8.000000e-08    -8.000000e-08   131.805807          0.000019   
4570     6.330000e-06    -6.330000e-06   132.064700          0.003650   
2916     2.250000e-05    -2.250000e-05   132.625470          0.005800   
4080     3.369000e-04    -3.369000e-04   149.172880          0.001840   

      koi_time0bk_err2  ...  koi_steff_err2  koi_slogg  koi_slogg_err1  \
1128         -0.001030  ...            -105      4.185           0.182   
1842         -0.006400  ...            -193      4.483           0.054   
5681         -0.000111  ...            -208      3.996           0.306   
4295         -0.000561  ...            -189      3.558           0.353   
1729         -0.002940  ...            -142      4.588           0.039   
...                ...  ...             ...        ...             ...   
3462         -0.012000  ...            -148      4.503           0.071   
6568         -0.000019  ...            -250      4.182           0.180   
4570         -0.003650  ...            -242      4.038           0.406   
2916         -0.005800  ...            -428      4.137           0.170   
4080         -0.001840  ...            -112      2.877           0.168   

      koi_slogg_err2  koi_srad  koi_srad_err1  koi_srad_err2         ra  \
1128          -0.098     1.336          0.209         -0.256  289.34143   
1842          -0.216     0.955          0.297         -0.099  286.95844   
5681          -0.165     1.990          0.578         -0.707  299.21390   
4295          -0.118     3.177          0.588         -1.372  281.89307   
1729          -0.097     0.769          0.122         -0.066  283.39825   
...              ...       ...            ...            ...        ...   
3462          -0.632     0.836          0.887         -0.074  296.82028   
6568          -0.180     1.482          0.442         -0.362  295.49411   
4570          -0.145     1.501          0.371         -0.603  289.74249   
2916          -0.187     1.684          0.501         -0.410  291.54343   
4080          -0.112     8.121          1.096         -2.556  296.92874   

            dec  koi_kepmag  
1128  46.988239      13.929  
1842  42.541382      14.699  
5681  40.458382      12.777  
4295  44.827461      12.733  
1729  46.689789      14.628  
...         ...         ...  
3462  42.514198      15.758  
6568  40.406204      13.585  
4570  39.267059       7.899  
2916  38.048759      13.458  
4080  47.882950       9.715  

[5592 rows x 40 c

In [112]:
y_train

array([2, 1, 3, ..., 3, 2, 2])

# Pre-processing

Scale the data using the MinMaxScaler and perform some feature selection

In [113]:
# Scale your data
from sklearn.preprocessing import MinMaxScaler
X_minmax = MinMaxScaler().fit(X_train)
#y_minmax = MinMaxScaler().fit(y_train)

X_train_scaled = X_minmax.transform(X_train)
X_test_scaled = X_minmax.transform(X_test)
#y_train = y_minmax.transform(y_train)
#y_test = y_minmax.transform(y_test)


# Train the Model



In [114]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(solver='liblinear', random_state=0)
classifier

LogisticRegression(random_state=0, solver='liblinear')

In [115]:
classifier.fit(X_train_scaled, y_train)

LogisticRegression(random_state=0, solver='liblinear')

In [116]:
print(f"Training Data Score: {classifier.score(X_train_scaled, y_train)}")
print(f"Testing Data Score: {classifier.score(X_test_scaled, y_test)}")



Training Data Score: 0.8385193133047211
Testing Data Score: 0.8477483917083631


In [117]:
#Dinnara
predictions = classifier.predict(X_test)
print(f"First 10 Predictions:   {predictions[:10]}")
print(f"First 10 Actual labels: {y_test[:10].tolist()}")

First 10 Predictions:   [3 3 3 3 3 3 3 3 3 3]
First 10 Actual labels: [3, 2, 1, 2, 2, 1, 1, 1, 2, 2]


In [118]:
pd.DataFrame({"Prediction": predictions, "Actual": y_test}).reset_index(drop=True)

Prediction  Actual
0              3       3
1              3       2
2              3       1
3              3       2
4              3       2
...          ...     ...
1394           3       3
1395           3       3
1396           3       1
1397           3       3
1398           3       1

[1399 rows x 2 columns]

In [119]:
classifier.classes_

array([1, 2, 3])

In [120]:
classifier.intercept_

array([-1.52881595,  1.14322142, -0.05112482])

In [121]:
classifier.coef_

array([[-2.73576394e+00, -3.73662284e+00, -3.23244059e+00,
        -2.77174001e+00, -3.61972222e+00, -1.97890688e+00,
         4.50090922e-01,  5.59108440e-02, -4.12142947e+00,
         2.59261351e+00, -5.58136898e-01, -2.67720374e+00,
        -1.34471165e+00,  1.31049873e+00, -4.36525578e+00,
         2.83643983e+00, -1.50428928e+00, -3.04306903e-02,
        -1.49838526e+00, -9.06455302e-02, -1.35282372e-01,
        -1.45111913e+00, -2.50911985e+00, -4.74973524e-02,
        -1.00593436e-01, -1.48921173e+00,  5.87646210e-01,
         1.55924344e+00,  4.90020919e-01, -3.69143658e+00,
         1.10258542e+00,  1.34752483e+00, -7.33790541e-01,
         1.93974577e+00, -5.84786025e-01, -1.26012864e+00,
        -1.17088918e+00, -5.88794414e-01,  5.15572103e-01,
        -1.17984974e-01],
       [-6.19274058e+00, -3.72195203e+00, -4.69915380e+00,
        -3.64177988e+00,  2.95730533e+00,  1.03531004e+00,
         1.07911381e-01, -6.90463474e-03,  3.12260785e+00,
        -1.97938642e+00,  2.59

In [122]:
classifier.predict(X)

array([3, 3, 3, ..., 3, 3, 3])

# Hyperparameter Tuning

Use `GridSearchCV` to tune the model's parameters

In [123]:
# Create the GridSearchCV model
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(solver='liblinear', random_state=0)

# Create the GridSearch estimator along with a parameter object containing the values to adjust
from sklearn.model_selection import GridSearchCV
param_grid = {'C': [1, 5, 10, 50]}
    
grid = GridSearchCV(classifier, param_grid, verbose=3, return_train_score=True)

In [124]:
# Train the model with GridSearch
grid.fit(X_train_scaled, y_train)

Fitting 5 folds for each of 4 candidates, totalling 20 fits
[CV 1/5] END ...........C=1;, score=(train=0.834, test=0.836) total time=   0.1s
[CV 2/5] END ...........C=1;, score=(train=0.834, test=0.831) total time=   0.0s
[CV 3/5] END ...........C=1;, score=(train=0.838, test=0.834) total time=   0.0s
[CV 4/5] END ...........C=1;, score=(train=0.838, test=0.836) total time=   0.0s
[CV 5/5] END ...........C=1;, score=(train=0.837, test=0.838) total time=   0.0s
[CV 1/5] END ...........C=5;, score=(train=0.850, test=0.853) total time=   0.1s
[CV 2/5] END ...........C=5;, score=(train=0.854, test=0.847) total time=   0.0s
[CV 3/5] END ...........C=5;, score=(train=0.855, test=0.852) total time=   0.0s
[CV 4/5] END ...........C=5;, score=(train=0.854, test=0.849) total time=   0.0s
[CV 5/5] END ...........C=5;, score=(train=0.855, test=0.843) total time=   0.1s
[CV 1/5] END ..........C=10;, score=(train=0.855, test=0.866) total time=   0.1s
[CV 2/5] END ..........C=10;, score=(train=0.862,

GridSearchCV(estimator=LogisticRegression(random_state=0, solver='liblinear'),
             param_grid={'C': [1, 5, 10, 50]}, return_train_score=True,
             verbose=3)

In [125]:
print(grid.best_params_)
print(grid.best_score_)

{'C': 50}
0.8680239352475777


In [126]:
#Dinnara
predictions = grid.predict(X_test)

In [127]:
print(f"First 10 Predictions:   {predictions[:10]}")
print(f"First 10 Actual labels: {y_test[:10].tolist()}")

First 10 Predictions:   [1 1 3 1 1 1 1 1 1 3]
First 10 Actual labels: [3, 2, 1, 2, 2, 1, 1, 1, 2, 2]


In [128]:
# Calculate classification report
from sklearn.metrics import classification_report
print(classification_report(y_test, predictions,
                            target_names=["blue", "red", "white"]))

              precision    recall  f1-score   support

        blue       0.24      0.60      0.35       340
         red       0.00      0.00      0.00       338
       white       0.65      0.51      0.57       721

    accuracy                           0.41      1399
   macro avg       0.30      0.37      0.31      1399
weighted avg       0.39      0.41      0.38      1399



/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [129]:
results = pd.DataFrame(grid.cv_results_)
results

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0       0.041672      0.012212         0.000534        0.000178       1   
1       0.049113      0.000961         0.000391        0.000051       5   
2       0.054785      0.000967         0.000359        0.000068      10   
3       0.088491      0.006148         0.000440        0.000088      50   

      params  split0_test_score  split1_test_score  split2_test_score  \
0   {'C': 1}           0.835567           0.831099           0.833631   
1   {'C': 5}           0.852547           0.847185           0.851521   
2  {'C': 10}           0.865952           0.853441           0.866726   
3  {'C': 50}           0.879357           0.866845           0.873882   

   split3_test_score  ...  mean_test_score  std_test_score  rank_test_score  \
0           0.836315  ...         0.834943        0.002398                4   
1           0.848837  ...         0.848533        0.003534                3   
2           0.853309  ...         0.858011        0.006878                2   
3           0.857782  ...         0.868024        0.007776                1   

   split0_train_score  split1_train_score  split2_train_score  \
0            0.833892            0.833892            0.837729   
1            0.849765            0.854013            0.855163   
2            0.855131            0.861838            0.863210   
3            0.865862            0.876369            0.874609   

   split3_train_score  split4_train_score  mean_train_score  std_train_score  
0            0.837506            0.837282          0.836060         0.001776  
1            0.854269            0.854716          0.853585         0.001950  
2            0.861869            0.863210          0.861051         0.003022  
3            0.872150            0.874162          0.872630         0.003641  

[4 rows x 21 columns]

# Save the Model

In [130]:
# save your model by updating "your_name" with your name
# and "your_model" with your model variable
# be sure to turn this in to BCS
# if joblib fails to import, try running the command to install in terminal/git-bash
import joblib
filename = 'your_name.sav'
joblib.dump(your_model, filename)

NameError: name 'your_model' is not defined